# Generated by Django 4.2.1 on 2023-05-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_id_alter_comments_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reporter_name',
        ),
    ]
