# Generated by Django 4.2.1 on 2023-05-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ticket_reporter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
