# Generated by Django 4.2.1 on 2023-05-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticket_assignee_alter_ticket_reporter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': [-1]},
        ),
    ]
