# Generated by Django 4.2.1 on 2023-05-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ticket_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_name',
        ),
    ]
