# Generated by Django 4.2.1 on 2023-05-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_comments_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date_created']},
        ),
    ]
